#!/bin/bash

##
#	do NOT poison a nix shell
##
grep -q IN_NIX_SHELL <(env) && return


##
#	always-section
# is executed even when running non-interactively (e.g. from a Vim session)
##
# shellcheck source=/Users/sirio/.nix-profile/etc/profile.d/nix.sh
source "$HOME/.nix-profile/etc/profile.d/nix.sh"

# allow coredumps
ulimit -c unlimited >/dev/null 2>&1
# e.g. because git annex opens many files
(($(ulimit -n) < 2048)) && ulimit -n 2048 >/dev/null 2>&1

# color support
case "$TERM" in
xterm-color|*-256color)
	# color terminal
	PS1='\[\033[1;31m\]\u\[\033[0m\]@\[\033[1;32m\]\h\[\033[0m\]:\[\033[1;34m\]\w\[\033[0m\]\$ '
	# Use dircolors standard database '-b' for simplicity
	# we _always_ have dircolors (... we _always_ have coreutils, right?)
	eval "$(dircolors -b)"
	alias ls='ls --color=auto -F'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	;;
*)
	# boring terminal
	PS1='\u@\h:\w\$ '
	;;
esac


##
#	aliases and functions for convenience
##
alias bch='bean-check'

alias btcblock='echo $(bitcoin-cli getblockcount 2>&1)/$(wget -O - http://blockchain.info/q/getblockcount 2>/dev/null)'
alias btcinfo='bitcoin-cli getwalletinfo'

nixpub() { nix-build --tarball-ttl 0 --max-jobs auto --cores 0 --keep-going "$@" | cachix push siriobalmelli-nixpkgs; };

alias cht='cht.sh'

alias cscopez='cscope -bqRU'

alias la='ls -A'
alias ll='ls -lha'

alias lsusb='[ $(uname) = "Darwin" ] && ioreg -p IOUSB || lsusb'

alias mr='time mr -j$(nproc) --stats'

#	tarify()
# Archive $1 into a tar.bz2 file and then delete it
tarify() { XZ_OPT="-Csha256 -9 -T0" nice -n 10 -- tar --xz -cf "$1".tar.xz "$1" && rm -rf "$1"; }
untarify() { nice -n 10 -- tar --xz -xf "$1" && rm -rf "$1"; }

alias tmp='cd $(mktemp -d)'


## a simple, workable, cross-platform clipboard
#CLIPBOARD=~/.clipboard
#shopt -s expand_aliases  # that works even inside a vim '!'
#alias yp='cat >"$CLIPBOARD"'
#alias pp='touch "$CLIPBOARD" && cat "$CLIPBOARD"'


##
#	interactive-section
# things that pollute the environment should go below here
##
if [[ ! $- == *i* ]]; then
	# OS or default bashrc may have some funky ideas about stty
	# that shouldn't be seen by non-interactive shells
	# ... except this somehow creates
	# "stty: 'standard input': Inappropriate ioctl for device"
	# so not always a good idea (facepalm)
	# stty sane
	return
fi
# fix "stty: 'standard input': Inappropriate ioctl for device"
alias stty='stty 2>/dev/null'


##
#	gpg auth with SSH - only in interactive section
##
GPG_TTY=$(tty)
export GPG_TTY
SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export SSH_AUTH_SOCK
gpg-connect-agent updatestartuptty /bye >/dev/null
gpg-connect-agent /bye
# to get SSH key, use: gpg --export-ssh-key sirio@b-ad.ch
# to list all keys, use 'ssh-add -L'


## lock tty on Ctrl-S (DC3), release with Ctrl-Q (DC1)
stty ixon

export XDG_CONFIG_HOME=~/.config

export BASH_ENV=~/.bashrc
export EDITOR=vim
export PAGER=less

# improve general commandline experience
alias cat=bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# hack Python to see nix
PYTHONPATH=$(find ~/.nix-profile/lib -type d -path "*/python*/site-packages" | tr '\n' ':')$PYTHONPATH
export PYTHONPATH

# hack C compilation to see installed libraries
export PKG_CONFIG_PATH=~/.nix-profile/lib/pkgconfig
export CPATH=~/.nix-profile/include/
export LIBRARY_PATH=~/.nix-profile/lib

# gopass completion
# TODO: broken (possibly quoting or similar?)
#$(gopass completion bash)
alias psw='gopass show -C'


# Eternal bash history, found here: https://stackoverflow.com/questions/9457233/unlimited-bash-history
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
#export HISTFILESIZE=
#export HISTSIZE=
# ok, unlimited might be a bit nuts ... let's stick to 15k lines
export HISTFILESIZE=15000
export HISTSIZE=15000
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
