##
#	do NOT poison a nix shell
##
if grep -q IN_NIX_SHELL <(env); then return; fi

##
#	always-section
# is executed even when running non-interactively
##

# source nix
source $HOME/.nix-profile/etc/profile.d/nix.sh

# allow coredumps
ulimit -c unlimited >/dev/null 2>&1

# No locking on Ctrl-S
stty -ixon

alias gd="git diff"
alias tmp='cd $(mktemp -d)'

# a simple, workable, cross-platform clipboard
CLIPBOARD=~/.clipboard
shopt -s expand_aliases  # that works even inside a vim '!'
alias yp='cat >"$CLIPBOARD"'
alias pp='touch "$CLIPBOARD" && cat "$CLIPBOARD"'


##
#	interactive-section
# skip these steps if running e.g. inside a script
##
case $- in
    *i*) ;;
      *) return;;
esac

# Eternal bash history, found here: https://stackoverflow.com/questions/9457233/unlimited-bash-history
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# color support
case "$TERM" in
xterm-color|*-256color)
	# color terminal
	PS1='\[\033[01;32m\]\u\[\033[00m\]@\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
	# enable color support of ls and also add handy aliases
	if [ -x /usr/bin/dircolors ]; then
	    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	    alias ls='ls --color=auto'
	    alias dir='dir --color=auto'
	    alias vdir='vdir --color=auto'

	    alias grep='grep --color=auto'
	    alias fgrep='fgrep --color=auto'
	    alias egrep='egrep --color=auto'
	fi
	;;
*)
	# boring terminal
	PS1='\u@\h:\w\$ '
	;;
esac

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# non-interactive, non-login shell should still source ~/.bahsrc
export BASH_ENV=~/.bashrc
export EDITOR=vim

# hack Python to see nix
export PYTHONPATH=$(find -L ~/.nix-profile -path "*/python*/site-packages" -type d | tr '\n' ':')$PYTHONPATH
