##
#	do NOT poison a nix shell
##
grep -q IN_NIX_SHELL <(env) && return


##
#	always-section
# is executed even when running non-interactively (e.g. from a Vim session)
##
source $HOME/.nix-profile/etc/profile.d/nix.sh

# allow coredumps
ulimit -c unlimited >/dev/null 2>&1

# color support
case "$TERM" in
xterm-color|*-256color)
	# color terminal
	PS1='\[\033[01;32m\]\u\[\033[00m\]@\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
	# assume we _always_ have dircolors
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	;;
*)
	# boring terminal
	PS1='\u@\h:\w\$ '
	;;
esac

alias bch='bean-check'

alias btcblock='echo $(bitcoin-cli getblockcount 2>&1)/$(wget -O - http://blockchain.info/q/getblockcount 2>/dev/null)'
alias btcinfo='bitcoin-cli getwalletinfo'

alias cht='cht.sh'

# don't conflict with e.g. 'gs' (ghostscript)
alias gad="git add"
alias gbr="git branch"
alias gco="git checkout"
alias gct="git commit"
alias gdc="git diff --cached"
alias gdf="git diff"
alias gfh="git fetch"
alias glg="git log"
alias gmg="git merge"
alias gph="git push"
alias gpl="git pull"
alias gpt="git push --tags"
alias gpy="git cherry-pick"
alias grb="git rebase"
alias gre="git remote"
alias grh="git reset --hard"
alias grs="git reset"
alias gst="git status"
alias gtg="git tag"

alias la='ls -A'
alias ll='ls -lha'
alias tmp='cd $(mktemp -d)'

## a simple, workable, cross-platform clipboard
#CLIPBOARD=~/.clipboard
#shopt -s expand_aliases  # that works even inside a vim '!'
#alias yp='cat >"$CLIPBOARD"'
#alias pp='touch "$CLIPBOARD" && cat "$CLIPBOARD"'


##
#	interactive-section
# things that pollute the environment should go below here
##
if [[ ! $- == *i* ]]; then
	# OS or default bashrc may have some funky ideas about stty
	# that shouldn't be seen by non-interactive shells
	stty sane
	return
fi

## lock tty on Ctrl-S (DC3), release with Ctrl-Q (DC1)
stty ixon

export BASH_ENV=~/.bashrc
export EDITOR=vim
export PAGER=less

# hack Python to see nix
export PYTHONPATH=$(find ~/.nix-profile/lib -type d -path "*/python*/site-packages" | tr '\n' ':')$PYTHONPATH

# hack C compilation to see installed libraries
export PKG_CONFIG_PATH=~/.nix-profile/lib/pkgconfig
export CPATH=~/.nix-profile/include/
export LIBRARY_PATH=~/.nix-profile/lib

# gopass completion
# TODO: broken (possibly quoting or similar?)
#$(gopass completion bash)

# Eternal bash history, found here: https://stackoverflow.com/questions/9457233/unlimited-bash-history
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
